### ISSUE TITLE
Revisão de requisitos - Teams

### ISSUE THREAD

**Issue by leonardopach** [Professor-Dudarts/ludus_service_teams#10]

**Comment by leonardopach** [comment]
`

[US_1.-.Gerenciamento.de.Times.de.Futebol.pdf](https://github.com/Professor-Dudarts/ludus_service_teams/files/11127806/US_1.-.Gerenciamento.de.Times.de.Futebol.pdf)

**Comment by bauersaba** [comment]
Concluido
