### ISSUE TITLE
Teste de qualidade e consistência

### ISSUE THREAD

**Issue by bauersaba** [Professor-Dudarts/ludus_service_teams#19]

**Comment by leonardopach** [comment]
Evidencias de teste - 

[US_1.-.Gerenciamento.de.Times.de.Futebol.pdf](https://github.com/Professor-Dudarts/ludus_service_teams/files/11127916/US_1.-.Gerenciamento.de.Times.de.Futebol.pdf)



Revisado - ![Image](https://user-images.githubusercontent.com/61167606/229248565-a8c3b291-5968-48bd-86bc-87d32999687a.png)

**Comment by bauersaba** [comment]
fechado ; qa ok
