### ISSUE TITLE
Levantamento de requisitos - Teams

### ISSUE THREAD

**Issue by bauersaba** [Professor-Dudarts/ludus_service_teams#5]
Tarefa para criação de documento com os requisitos do serviço 'times"

**Comment by bauersaba** [comment]
Link para documento compartilhado.

https://1drv.ms/w/s!AjECpdzBZiJFgsYfGWl_tOlbG9fpNA?e=filoWd

**Comment by bauersaba** [comment]
add documento em pdf para revisão



[Doc.Requisitos_teams.pdf](https://github.com/Professor-Dudarts/ludus_service_teams/files/10949735/Doc.Requisitos_teams.pdf)

**Comment by leonardopach** [comment]
[US_1 - Gerenciamento de Times de Futebol.docx](https://github.com/Professor-Dudarts/ludus_service_teams/files/10952209/US_1.-.Gerenciamento.de.Times.de.Futebol.docx)

**Comment by bauersaba** [comment]
Fechando
