### ISSUE TITLE
Diagrama de classes - Teams

### ISSUE THREAD

**Issue by bauersaba** [Professor-Dudarts/ludus_service_teams#7]
Tarefa para criação de documento com o diagrama de classes

**Comment by bauersaba** [comment]
![Image](https://user-images.githubusercontent.com/61196859/224518006-c8638b9d-08c2-4c72-815a-30af982a168a.png)

**Comment by bauersaba** [comment]
Diagrama revisado. 



![Image](https://user-images.githubusercontent.com/61196859/226204275-f669b84b-8489-489a-9bcc-384438aa6fa5.png)

**Comment by juniorsn1409** [comment]
documento revisado.
