### ISSUE TITLE
Arquitetura do Sistema - Teams

### ISSUE THREAD

**Issue by bauersaba** [Professor-Dudarts/ludus_service_teams#8]
Tarefa para criação de documento com a Arquitetura do sistema.

**Comment by RafaAlm** [comment]
![Image](https://user-images.githubusercontent.com/68666224/224604468-de130f89-211b-47fd-a56b-e02df26c7757.png)

**Comment by RafaAlm** [comment]
Olá pessoal, estou aberto para conversar e rever algumas coisas caso precise.

**Comment by bauersaba** [comment]
Documento revisado.
